// Generated by CoffeeScript 1.8.0
(function() {
  var marked;

  marked = require('./marked');

  marked.pluginCompiler = require("./pluginCompiler");

  marked.tocCompiler = require("./tocCompiler");

  marked.ReactRenderer = require("./ReactRenderer");

  (function() {
    var newLexer, oldLexer;
    oldLexer = marked.lexer;
    newLexer = function(data, options) {
      var toks;
      toks = oldLexer(data, options);
      return marked.pluginCompiler(toks, {
        'TOC': marked.tocCompiler
      });
    };
    marked.Lexer.lex = newLexer;
    return marked.lexer = newLexer;
  })();

  module.exports = marked;

}).call(this);

//# sourceMappingURL=markedtoc.js.map
